version: '2.0'

services:

  application:
    build: .
    ports:
      - '127.0.0.1:8000:8000'
    volumes:
      - ./env/prod.env:/bc-edu/env/dev.env

  postgres:
    image: postgres:15-alpine
    env_file:
      - ./env/prod.env
    volumes:
      - ./env/postgres/data:/var/lib/postgresql/data
      - ./env/postgres/logs:/logs