version: '2.0'

services:

  application:
    build: .
    ports:
      - '0.0.0.0:3030:8000'
    depends_on:
      - postgres
    volumes:
      - /mnt/bc-edu/logs:/logs

  postgres:
    image: postgres:14-alpine
    #ports:
    #  - '5432:5432'
    env_file:
      - ./env/dev.env
    volumes:
      - /mnt/bc-edu/postgres/data:/var/lib/postgresql/data
      - /mnt/bc-edu/postgres/logs:/logs
